spring:
  application:
    name: Plan-API
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    password: Kunal@123
    username: root
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: console
server:
  port: 9090
 

plan-api:
  messages:
    PlanSaved     : PlanSaved
    PlanFail      : PlanSavedFail
    UpdatePlan    : UpdatePlan
    UpdatePlanFail: UpdatePlanFail
    DeletePlan    : DeletePlanSuccess
    DeletePlanFail: DeletePlanFail
    PlanStatus    : Changed
    PlanStatusFail: Not Changed